services:
  nextjs:
    image: phamducbinh/nextjs-app:latest
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
