services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: phamducbinh171/nextjs-app:latest
    container_name: nextjs-app
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
